apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-service-monitor
  labels:
    release: prometheus # Ensure Prometheus is set up with this release label
spec:
  endpoints:
  - interval: 30s
    port: flask-contacts-service
    scrapeTimeout: 10s
  selector:
    matchLabels:
      app: flask-app # Match the labels in the Service