apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template: #pod defintion
    metadata:
      labels:
        app: flask-app
    spec: # container specs
      containers:
        - name: flask-app
          image: idror/flask-contacts-appid:latest
          ports:
            - containerPort: 5052
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: db_url
          readinessProbe:
            httpGet:
              path: /
              port: 5052
          volumeMounts:
          - name: flask-app-images
            mountPath: /app/static/images
      volumes:
        - name: flask-app-images
          persistentVolumeClaim:
            claimName: flask-app-images

---
apiVersion: v1
kind: Service
metadata:
  name: flask-contacts-app-service
  labels:
    app: flask-contact-service
spec:
  selector:
    app: flask-app
  type: LoadBalancer # external service which can be accessed from outside the cluster
  ports:
    - name: flask-contacts-service
      protocol: TCP
      port: 5053
      targetPort: 5052